# config/example-config.yaml
kubeconfig: "/home/usuario/.kube/config"
inCluster: false

logLevel: info

defaultNamespace: ""
requestTimeoutSeconds: 30

# Escopo de acesso (pensando em RBAC)
allowedApiGroups:
  - ""
  - route.openshift.io
  - build.openshift.io
  - image.openshift.io
  - project.openshift.io
  - kubevirt.io
